Tc11 verify subscription in cart page
MahmoudElSharkawyGS/AutomationExercisePractice pull request #12
Opened 2024-02-05 07:27 UTC by AlaaMahmoudFawzy

**[Pipeline Run URL](https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/7794867215)**

[Pipeline Run after resolving the change and conflicts.](https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/7819758845)

2024-02-07 15:34 UTC, MahmoudElSharkawyGS requested changes
- Please resolve the conflicts
- Please make sure to format your code
- Please make sure to have empty line between methods
- Please make sure to not have 2 empty lines anywhere

2024-02-07 15:34 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/CartTests.java
> +        testUserData = new SHAFT.TestData.JSON("src/test/resources/testDataFiles/RegisterUser.json");
We should only have 1 to 1 relationship between the test data json file and test class.
Please add the registration data in the corresponding test data json file with unique names to the test case.

2024-02-08 10:45 UTC, MostafaAgamyGizaSystems approved these changes

2024-02-12 15:24 UTC, MahmoudElSharkawyGS approved these changes

2024-02-12 15:24 UTC, merged