verifying subscription in home page
MahmoudElSharkawyGS/AutomationExercisePractice pull request #13
Opened 2024-02-05 08:38 UTC by basant-lazem

2024-02-07 15:48 UTC, MahmoudElSharkawyGS requested changes
- Please make sure to execute the pipeline and add the execution link here
- Please make sure to format your code
- Please make sure to have empty line between methods
- Please make sure to not have 2 empty lines anywhere

2024-02-07 15:48 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/HomePage.java
> +    private  final By successMsg = By.xpath("");
We should not have empty value locator

2024-02-07 15:48 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/HomePage.java
> +    private final By subscribeButton = By.xpath("//*[@id=\"subscribe\"]/i");
Please replace the \" to '

2024-02-07 15:48 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/HomePage.java
> +    private final By subscriptionEmail = By.xpath("//*[@id=\"susbscribe_email\"]");
We can use the id locator directly

2024-02-07 15:48 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/HomePage.java
> +    private final By subscribeButton = By.xpath("//*[@id=\"subscribe\"]/i");
It's not recommended to use * in the xpath, please add the tag names here.

2024-02-07 15:48 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/HomePage.java
> +//    }
Please remove any commented code

2024-02-11 10:05 UTC, basant-lazem commented on src/main/java/com/gizasystems/automationexercise/pages/HomePage.java
> +    private final By subscribeButton = By.xpath("//*[@id=\"subscribe\"]/i");
It gives an error when do so.

2024-02-12 15:28 UTC, MahmoudElSharkawyGS commented
@basant-lazem Please resolve the conflicts and execute the pipeline again.

2024-02-13 08:38 UTC, basant-lazem commented
https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/7883741367

2024-02-18 07:21 UTC, MahmoudElSharkawyGS requested changes
You have 10 files changed now :D

2024-02-22 14:41 UTC, basant-lazem commented
Pipeline :
https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/8005610384

2024-02-25 09:07 UTC, MahmoudElSharkawyGS requested changes
Please make sure to reformat your code.
Please make sure to execute the pipeline and share the link.

2024-02-25 09:07 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/CheckOutPage.java
> +    private  final By addressVerifiycation_address1 = By.xpath("/html/body/section/div/div[3]/div/div[1]/ul/li[4]");
Please refactor this xpath to be relative not absolute.

2024-02-25 09:07 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/SignupPage.java
> +//        driver.element().click(continueBtn_link);
Please remove commented code.

2024-02-25 09:07 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/SignupPage.java
> +
Why changing the already working code here? Please revert those changes here.

2024-02-25 09:07 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/test/verifyingSubscriptionInHomePage.java
> +    }
Configuration methods (Before & After) should be at the bottom of the test class as agreed.

2024-03-03 08:58 UTC, basant-lazem commented
pipeline :
https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/8129035917

2024-03-12 09:49 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/test/verifyingSubscriptionInHomePage.java
> +        new Footer(driver).verifySubscriptionText(testUser.getTestData("subText")).enterSubscriptionEmail(testUser.getTestData("UserMail.GuiTimeStamp") + timeStamp + "@gizasystems.com").clickOnSubscr
Please make sure to align the methods chinning in the test case as agreed (a new line for every method for better readability)

2024-03-12 11:24 UTC, MahmoudElSharkawyGS reviewed
Don't forget the naming conventions (lowerCamelCase) please.

2024-03-12 14:01 UTC, MahmoudElSharkawyGS requested changes

2024-03-12 14:01 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/verifyingSubscriptionInHomePage.java
> +    @Test(description = "Verify Subscription is on Home Page")
Please add Description and Tms annotations (@TmsLink should have this value ("55512381")) 
![image](https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/assets/46620469/d0361c60-ac59-4abe-91e8-5873b4096587)

2024-03-13 08:49 UTC, merged