Tc2 login with correct email and password
MahmoudElSharkawyGS/AutomationExercisePractice pull request #14
Opened 2024-02-05 11:49 UTC by MariamAbduallah

- The following PR contains the automation of TC#2 login with correct email and password.
Steps needs to be validated: 
1. Launch browser
2. Navigate to url ['http://automationexercise.com'](https://automationexercise.com/)
3. Verify that home page is visible successfully
4. Click on 'Signup / Login' button
5. Verify 'Login to your account' is visible
6. Enter correct email address and password
7. Click 'login' button
8. Verify that 'Logged in as username' is visible
9. Click 'Delete Account' button
10. Verify that 'ACCOUNT DELETED!' is visible

2024-02-07 15:53 UTC, MahmoudElSharkawyGS requested changes
Please check the pipeline execution link as it's not working.

2024-02-07 15:53 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/login/LoginWithCorrectEmailAndPasswordTest.java
> +
Please this empty line

2024-02-07 15:53 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/login/LoginWithCorrectEmailAndPasswordTest.java
> +
Pleas remove one empty line of those

2024-02-07 15:53 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/SignupLoginPage.java
>      }
Please add empty line here

2024-02-07 15:53 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/login/LoginWithCorrectEmailAndPasswordTest.java
> +        registerTestData = new SHAFT.TestData.JSON("src/test/resources/testDataFiles/RegisterUser.json");
We should only have 1 to 1 relationship between the test data json file and test class.
Please add the registration data in the corresponding test data json file with unique names to the test case.

2024-02-08 11:26 UTC, MariamAbduallah commented
> Please check the pipeline execution link as it's not working.

it works for me.. what was the problem ? , try to copy and paste it in a new tab an let me know.
![Uploading pipeline.jpg…]()

2024-02-12 15:30 UTC, MahmoudElSharkawyGS commented
@MariamAbduallah 
Please check the conflicts and resolve them.
Please check the pipeline execution as no test cases were executed; And please execute it again.

2024-02-13 11:01 UTC, MahmoudElSharkawyGS commented
https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/7885380784

2024-02-13 11:01 UTC, MahmoudElSharkawyGS approved these changes

2024-02-13 11:01 UTC, merged