Tc21 add review
MahmoudElSharkawyGS/AutomationExercisePractice pull request #24
Opened 2024-02-08 15:04 UTC by HadeerAlaa1

[Kindly check pipeline run 
](https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/7831507143)

2024-02-11 09:45 UTC, MahmoudElSharkawyGS requested changes
Please make sure to format your code using (alt + ctrl + L)

2024-02-11 09:45 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/HomePage.java
Why delete all empty lines between method here?

2024-02-11 09:45 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/NavigationBar.java
> +    @Step("Handle ADS")
Please add empty line here

2024-02-11 09:45 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/NavigationBar.java
> +    }
Why handling the add in the navigation bar page?
Also, I believe we already have a method for this (please check the utils package).

2024-02-11 09:45 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/NavigationBar.java
> +
Please delete extra empty lines.

2024-02-11 09:45 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/ProductsPage.java
> +    private final By reviewSuccessAlert = By.cssSelector("div.alert-success.alert > span[style=\"font-size: 20px;\"]");
Let's check this locator together as I believe we can enhance it.

2024-02-11 09:45 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/reviews/AddReviewTests.java
> +        testData = new SHAFT.TestData.JSON("src/test/resources/testDataFiles/RegisterUser.json");
Only one test data file needed to maintain the 1 to 1 relationship between testdata file and test classes.

2024-02-11 09:45 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/reviews/AddReviewTests.java
> +        new ProductsPage(driver).clickOnViewProduct()
Why you need a new initialization while both actions on the same page; We need to maintain the fluency please.

2024-02-21 10:29 UTC, MahmoudElSharkawyGS commented
@HadeerAlaa1 Any updates regarding tis PR please?

2024-02-25 09:11 UTC, MahmoudElSharkawyGS commented
@HadeerAlaa1 Thank you for your efforts.
- Please resolve the conflicts
- Please make to execute the pipeline after every change and share the pipeline execution link here

2024-02-28 09:26 UTC, MahmoudElSharkawyGS commented
@HadeerAlaa1 the conflicts still not resolved

2024-02-29 10:29 UTC, HadeerAlaa1 commented
Please find the pipline link attached here, https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/8094504574

2024-02-29 15:29 UTC, HadeerAlaa1 commented
@MahmoudElSharkawyGS  kindly check my PR and here is the pipeline link 
 https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/8098460712

2024-03-14 10:29 UTC, closed without merging