Tc12 add products in cart
MahmoudElSharkawyGS/AutomationExercisePractice pull request #26
Opened 2024-02-11 14:14 UTC by Marina-Nabil-Gohar223

workflow : https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/7862497523

2024-02-13 08:53 UTC, MahmoudElSharkawyGS requested changes
Please make sure to execute the pipeline again after the comments changes.

2024-02-13 08:53 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/CartPage.java
> +    private final By secondProductTotal = By.xpath("//p[@class='cart_total_price'][normalize-space()='Rs. 400']");
- I believe we can enhance those locators (let's discuss this next session).
- Please remove the empty lines between the locators.

2024-02-13 08:53 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/CartPage.java
> +    }
navigation method is not a validation method, please move it to the top on the actions section.

2024-02-13 08:53 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/CartPage.java
> +    }
Those methods are not dynamic; What if we have only 1 item, or if we have more than 2 items?.
We need to make those methods dynamic, not only works with 2 items.

2024-02-13 08:53 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/NavigationBar.java
Delete this empty line here between the locators please.

2024-02-13 08:53 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/NavigationBar.java
> +
Delete one empty line of the two here please.

2024-02-13 08:53 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/ProductsPage.java
> +    private final By viewCartButton = By.xpath("//u[normalize-space()='View Cart']");
Locators names should be descripting what they are, not what they do (you can do more than one action on the same locator).
Also we can remove the empty line between them.
One more thing, I believe we can enhance those locators.

2024-02-13 08:53 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/ProductsPage.java
> +    }
Both methods are identical, we need to make one dynamic method.

2024-02-21 10:30 UTC, MahmoudElSharkawyGS commented
@Marina-Nabil-Gohar223 Any updates regarding tis PR please?

2024-02-21 16:21 UTC, Marina-Nabil-Gohar223 commented
> @Marina-Nabil-Gohar223 Any updates regarding tis PR please?


Yes, there is an update on the pull request

2024-02-25 09:16 UTC, MahmoudElSharkawyGS requested changes
- You are using alot of dynamic locators which sometime can complicate the cases; Let's discuss this please.
- Also, please make sure to delete any empty lines as agreed before.
- Please make sure to resolve any conflicts before pushing.
- Finally, please make sure to execute the pipeline again and every change and share the execution pipeline link.

2024-02-27 08:55 UTC, MahmoudElSharkawyGS requested changes

2024-02-27 08:55 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/CartPage.java
> +    }
- Not sure to accept those locators as the user wouldn't know the ids of the items, this should be something like the name of the item, not the id
- Please follow the naming convention for the parameters variables (lowerCamaelCase).. ID should be id

2024-02-27 08:55 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/ProductsPage.java
> +    }
- Not sure to accept those locators as the user wouldn't know the index of the items if the order changes, this should be something like the name of the item, not the index
- Please follow the naming convention for the parameters variables (lowerCamaelCase).. Index should be index.

2024-02-27 08:55 UTC, MahmoudElSharkawyGS commented on src/test/java/com/gizasystems/automationexercise/tests/shoppingCart/AddProductInCart.java
> +                .validateOnTotalPrice(2, testData.getTestData("SecondProduct.total"));
any data should be retrieved from the test data json file (we can't add index like this if we should put it :D)

2024-02-29 12:08 UTC, MahmoudElSharkawyGS approved these changes
Thank you!

2024-02-29 12:08 UTC, merged