TC17_Remove-Products-From-Cart
MahmoudElSharkawyGS/AutomationExercisePractice pull request #43
Opened 2024-02-29 19:14 UTC by HebaAbdelaziz911

2024-02-29 19:20 UTC, HebaAbdelaziz911 commented
https://github.com/MahmoudElSharkawyGS/AutomationExercisePractice/actions/runs/8101417989
The pipeline link

2024-03-06 07:34 UTC, MahmoudElSharkawyGS requested changes

2024-03-06 07:34 UTC, MahmoudElSharkawyGS commented on src/main/java/com/gizasystems/automationexercise/pages/CartPage.java
> +        return By.xpath("//a[@class='cart_quantity_delete']["+ index + "]");
Please change the index value to something more dynamic and describable like the name of the product in your locator.

2024-03-10 11:23 UTC, MahmoudElSharkawyGS approved these changes

2024-03-10 11:24 UTC, merged